from ToolsFuns.Biology.biologyCommon import *
from ToolsFuns.Biology.novoproToolsBio import *
from ToolsFuns.Biology.protAgentTools import *
from ToolsFuns.Biology.qizhipeiTools import *
from ToolsFuns.Biology.extensionsTools import *


BIOLOGY_TOOLS_DICT = {
    "ComputePiMw": compute_pI_mW,
    "ComputeProtPara": compute_protein_parameters,
    "ComputeProtScale": predict_hydrophilicity,
    # "PredictPeptideMass": protein_tools.predict_peptidemass,
    # "PredictSignalp": protein_tools.predict_signalp,
    # "PredictTransmembrane":protein_tools.predict_transmembrane,
    "ComputeExtinctionCoefficient": compute_extinction_coefficient,
    "SequenceToPdb": sequence_to_pdb,
    "ComputeResidueAccuracy": compute_protein_sequence_residue_accuracy,
    "GenerateRandomMutation": generate_random_mutation_tool,
    "CipherOptimizer": cipher_optimizer_tool,
    "CalculatorPeptideProperty": peptide_property_calculator,
    "CalculatorOligonucleotide": oligonucleotide_calculator,
    "PredictSignalPeptide":protein_signal_peptide_prediction,
    "PredictTransmembraneRegion": protein_transmembrane_region_prediction,
    "ProteinCodonOptimization": protein_condonoptimizer,
    "DNARNACodonOptimization": DNA_condonoptimizer,
    "ComputeHydrophilicity": compute_hydrophilicity,
    "PredictSignalPeptide": predict_signalpeptide,
    "ComputeAnnealingTemperature": compute_tm,
    "ConvertingPeptide2SMILES": convert_polypeptide_to_smiles,
    "ProteinIsoelectricPointCalculator": compute_isoelectric_point,
    "ComputeAffinity": compute_affinity,
    "PeptideWeightCalculator": compute_polypeptide_weight,
    "PeptideFormulaCalculator": compute_polypeptide_formula,
    "DegenerateCodonCalculatorbyAminoAcid": compute_degeneracy,
    "OverlapPeptideLibraryDesign": design_overlappeptidelibrary,
    "AlanineScanningLibraryDesign": design_alaninescanninglibrary,
    "TruncationLibraryDesign": design_truncationlibrary,
    "PositionalScanningLibraryDesign": design_positionalscanninglibrary,
    "ProteaseDigestion": protease_digestion,
    "CDRLabelingAntibody": CDR_LabelingAntibody,
    "AntibodySequenceNumbering": number_antibodysequence,
    "CircularDNAAlignment": align_circularDNA,
    "CompareSequenceByLogExpectation": compare_multiple_sequence,
    "DoubleSequenceGlobalAlignment": align_double_sequence,
    "ProteinSolubilityPredictor": predict_protein_solubility,
    "InherentDisorderedRegionsPredictor": predict_inherent_disordered_regions,
    "DoubleSequenceLocalAlignment": align_double_sequence_local,
    "ProteinMotifAnalysis": analyse_protein_moti,
    "SequenceSimilarityCalculator": calculate_sequence_similarity,
    "ORFFind": find_orf,
    "TranslateDNAtoAminoAcidSequence": DNA_to_AminoAcid,
    "RepeatDNASequenceSearch": search_repeat_DNAsequence,
    "RepeatProteinSequenceSearch": search_repeat_proteinsequence,
    "PalindromicSequencesFinder": search_palindromic_sequences,
    "CalculateAminoAcidbyDegenerateCodon": degcon2aa,
    "ProteinNuclearLocalizationSequencePrediction": predict_nls,
    "SmallMoleculeSimilarityCalculation": compute_smiles_similarity,
    "DNAMolecularWeightCalculator": calculate_DNA_weight,
    "CpGIslandPrediction": predict_cpg,
    "PCRPrimerProperties": compute_primer_properties,
    "AminoAcidStatistics": count_amino_acid,
    "SummaryEnzymeCleavageSites": summary_enzyme_cleavage_sites,
    "RandomDNAGeneration": generate_random_DNA,
    "AnalyzeProteinCATHFromPDBID": analyze_protein_CATH_from_PDBID,
    "AnalyzeProteinLengthFromPDB": analyze_protein_length_from_PDB,
    "AnalyzeProteinSeqFromPDB": analyze_protein_seq_from_PDB,
    "FixPDBFile": fix_pdb_file,
    "FoldProtein": fold_protein,
    "CalculateEnergyFromSequence": calculate_energy_from_sequence,
    "CalculateForceFromSequence": calculate_force_from_sequence,
    "CalculateForceEnergyFromSequence": calculate_force_energy_from_sequence,
    "GenerateSequenceFromEnergy": generate_sequence_from_energy,
    "GetFASTAFromName": get_FASTA_from_name,
    "CalculateProteinANM": calculate_protein_ANM,
    "AnalyzeProteinStructure": analyze_protein_structure,
    # "DesignProteinFromCATH": design_protein_from_CATH,
    "DesignProteinAlpha": design_protein_alpha,
    "DesignProteinBeta": design_protein_beta,
    "DesignProteinAlphaBeta": design_protein_alpha_beta,
    "DesignProteinFromLength": design_protein_from_length,
    "SaveToCSVFile": save_to_csv_file,
    "FetchProteinStructureFromPDBID": fetch_protein_structure_from_PDBID,
    "GenerateMoleculeDescription": generate_molecule_description,
    "TexToMoleculeSELFIES": text_to_molecule_SELFIES,
    "PredictDrugTargetInteraction": predict_drug_target_interaction,
    "PredictHumanProteinInteraction": predict_human_protein_interaction,
    "PredictYeastProteinInteraction": predict_yeast_protein_interaction,
    "PredictProteinSolubility": predict_protein_solubility,
    "PredictProteinBinaryLocalization": predict_protein_binary_localization,
    "AnalyzeAtomCount": analyze_atom_count,
    "CalculateMolecularWeight": calculate_molecular_weight,
    "CalculateCenterOfMass": calculate_center_of_mass,
    "CalculateAverageCoordinates": calculate_average_coordinates,
    "CalculateAtomDistance": calculate_atom_distance,
    "GetAminoAcidFrequency": get_amino_acid_frequency,
    "GetReverseComplement": get_reverse_complement,
    "CalculateHydrophobicityAndPolarity": calculate_hydrophobicity_and_polarity,
    "PerformBlastQuery": perform_blast_query,
}   